name: Android CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permissão ao Gradle
        run: chmod +x ./gradlew

      - name: Criar keystore temporário (assinatura automática)
        run: |
          keytool -genkeypair \
            -alias androidkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass password \
            -keypass password \
            -keystore android_temp.keystore \
            -dname "CN=Android,O=App,C=BR"

      - name: Criar arquivo gradle.properties com configs de assinatura
        run: |
          echo "" >> gradle.properties
          echo "MYAPP_UPLOAD_STORE_FILE=android_temp.keystore" >> gradle.properties
          echo "MYAPP_UPLOAD_KEY_ALIAS=androidkey" >> gradle.properties
          echo "MYAPP_UPLOAD_STORE_PASSWORD=password" >> gradle.properties
          echo "MYAPP_UPLOAD_KEY_PASSWORD=password" >> gradle.properties

      - name: Build Release
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/**/*.apk

