name: Android CD

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checar c√≥digo
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Passo 3: Build Release APK
      - name: Build Release
        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=${{ secrets.KEYSTORE_FILE }} -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      # Passo 4: Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
